### ISSUE TITLE
node.js v17 以上版本程序启动失败问题

### ISSUE THREAD

**Issue by hxh2010** [kingdee/kdesign-pro#9]
同问题：[https://github.com/kingdee/kdesign/issues/423](https://github.com/kingdee/kdesign/issues/423)

```
node:internal/crypto/hash:68
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports.__webpack_modules__.57442.module.exports (/Users/hongxh/myapp1/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:135907:62)
    at NormalModule._initBuildHash (/Users/hongxh/myapp1/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:109317:16)
    at handleParseError (/Users/hongxh/myapp1/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:109371:10)
    at /Users/hongxh/myapp1/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:109403:5
    at /Users/hongxh/myapp1/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:109258:12
    at /Users/hongxh/myapp1/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:61157:3
    at iterateNormalLoaders (/Users/hongxh/myapp1/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:60998:10)
    at Array.<anonymous> (/Users/hongxh/myapp1/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:60989:4)
    at Storage.finished (/Users/hongxh/myapp1/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:47842:16)
    at /Users/hongxh/myapp1/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:47878:9
    at /Users/hongxh/myapp1/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:58734:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Comment by hxh2010** [comment]
同时，可使用项目中提供命令：
```
// 运行
npm run start:node17+


// 构建
npm run build:node17+
```
